//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloneAnalyser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clone
    {
        public int Id { get; set; }
        public Nullable<int> Nodes { get; set; }
        public string Source { get; set; }
        public string ACT { get; set; }
        public Nullable<int> CloneClusterId { get; set; }
    }
}
